/* dcollide-config.h. Generated by cmake from dcollide-config.h.cmake */

#ifndef DCOLLIDE_CONFIG_H
#define DCOLLIDE_CONFIG_H

#cmakedefine DCOLLIDE_USE_DOUBLE 1
#cmakedefine DCOLLIDE_USE_THREADS 1
#cmakedefine HAVE_ISNAN 1
#cmakedefine HAVE_SYS_TIME_H 1
#cmakedefine HAVE_EXECINFO_H 1

#cmakedefine DCOLLIDE_BROADPHASE_DEBUG 1

#endif

