/* dcollide-config_testapp.h. Generated by cmake from dcollide-config_testapp.h.cmake */

#ifndef DCOLLIDE_CONFIG_TESTAPP_H
#define DCOLLIDE_CONFIG_TESTAPP_H

#define DCOLLIDE_OGRE_PLUGIN_DIR "${OGRE_PLUGIN_DIRECTORY}"

#define DCOLLIDE_TESTAPP_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}"
#define DCOLLIDE_TESTAPP_SOURCE_PREFIX "${CMAKE_CURRENT_SOURCE_DIR}"

// AB: ogre uses #if on OGRE_WCHAR_T_STRINGS and OGRE_OGRE_RELEASE_ASSERT, but
// never defines them, which causes compiler warnings. fix that.
#define OGRE_WCHAR_T_STRINGS 0
#define OGRE_RELEASE_ASSERT 0

#endif
