/* dcollide-modelloader-config.h. Generated by cmake from dcollide-modelloader-config.h.cmake */

#ifndef DCOLLIDE_MODELLOADER_CONFIG_H
#define DCOLLIDE_MODELLOADER_CONFIG_H

#cmakedefine HAVE_LIB3DS 1

#endif

